dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: http://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: http://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
